[features]
report_metadata = false
report_mime = false
mask_highlights = false
send_notice = false
history = false
invite = false
autosave = false
send_errors_to_poster = false
reply_with_errors = false
partial_urls = false
nick_response = false

[parameters]
url_limit = 10
accept_lang = "en"
status_channels = []
nick_response_str = ""

[database]
path = ""
type = "in-memory"

[connection]
nickname = "url-bot-rs"
nick_password = ""
alt_nicks = ["url-bot-rs_"]
username = "url-bot-rs"
realname = "url-bot-rs"
server = "127.0.0.1"
port = 6667
password = ""
use_ssl = false
channels = ["#url-bot-rs"]
user_info = "Feed me URLs."
