owners = []
nickname = "user"
nick_password = "password"
alt_nicks = ["user_", "user__"]
username = "user"
realname = "Test User"
server = "chat.freenode.net"
port = 6697
password = ""
use_ssl = true
encoding = "UTF-8"
channels = ["#music"]
user_info = "Feed me URLs."
version = "0.1"
source = "https://github.com/nuxeh/url-bot-rs"
ping_time = 180
ping_timeout = 10
burst_window_length = 8
max_messages_in_burst = 15
should_ghost = false
ghost_sequence = []

[features]
mask_highlights = false
send_notice = false
