[features]
report_metadata = false
report_mime = false
mask_highlights = false
send_notice = false
history = false
invite = false
autosave = false

[parameters]
url_limit = 10
accept_lang = "en"

[database]
path = ""
type = "in-memory"

[connection]
nickname = "url-bot-rs"
nick_password = ""
alt_nicks = ["url-bot-rs_"]
username = "url-bot-rs"
realname = "url-bot-rs"
server = "chat.freenode.net"
port = 6697
password = ""
use_ssl = true
encoding = "UTF-8"
channels = []
user_info = "Feed me URLs."
source = "https://github.com/nuxeh/url-bot-rs"
ping_time = 180
ping_timeout = 10
burst_window_length = 8
max_messages_in_burst = 15
should_ghost = false
